## O POD É SUBSTITUÍDO PELO DEPLOYMENT, POR ESTE MOTIVO ESTÁ COMENTADO.
# apiVersion: v1
# kind: Pod
# metadata:
#   name: capacitacao-pod
#   namespace: capacitacao
#   labels:
#     name: capacitacao-pod
# spec:
#   imagePullSecrets:
#     - name: docker.totvs.io-credentials
#   containers:
#     - name: capacitacao-pod
#       image: docker.totvs.io/totvsmpn/mpn-chat-capacitacao
#       env:
#         - name: PORT
#           value: "3333"
#         - name: MONGO_URL
#           value: mongodb+srv://user:password@cluster0-zbd7b.mongodb.net/mpn-chat-capacitacao?retryWrites=true&w=majority
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "500m"
#       ports:
#         - containerPort: 3333
